name: biobb_md
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - ambertools=24.8
  - arpack=3.9.1
  - attrs=25.4.0
  - biobb_amber=5.1.0
  - biobb_analysis=5.1.0
  - biobb_common=5.1.0
  - biobb_gromacs=5.1.1               # Needs NBDSoftware version: https://github.com/NBDsoftware/biobb_gromacs
  - biobb_model=5.1.0
  - biobb_structure_checking=3.15.6
  - biobb_structure_utils=5.1.0
  - biopython=1.86
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - contourpy=1.3.2
  - cycler=0.12.1
  - fftw=3.3.10
  - fonttools=4.60.1
  - freetype=2.14.1
  - gromacs=2025.2
  - h2=4.3.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - joblib=1.5.2
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libboost=1.86.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcurl=8.17.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - lz4-c=1.10.0
  - matplotlib-base=3.10.7
  - mkl=2025.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf-fortran=4.6.2
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - parmed=4.3.0
  - perl=5.32.1
  - pillow=12.0.0
  - pip=25.3
  - psutil=7.1.3
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rpds-py=0.28.0
  - scipy=1.15.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tk=8.6.13
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xmltodict=1.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxt=1.3.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - amberutils==21.0
      - edgembar==3.0
      - mmpbsa-py==16.0
      - packmol-memgen==2025.1.29
      - pdb4amber==22.0
      - pymsmt==22.0
      - pytraj==2.0.6
      - sander==22.0
prefix: /home/pnavarro/.conda/envs/biobb_md
